CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ARTICLE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM_POINT START WITH 1 INCREMENT BY 1;