CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ARTICLE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SELECTED_ITEM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISCARD_ITEM START WITH 1 INCREMENT BY 1;